version: "3"

services:
  svetuz_bot:
    image: svetuz_bot
    container_name: svetuz_bot
    build: ./
    restart: always
    volumes:
      - ./:/app
networks:
  default:
    external:
      name: nginx-proxy